services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   ports:
  #     - "${APP_PORT:-8000}:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   profiles: ["dev"]

  # db:
  #   image: pgvector/pgvector:pg16
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-app}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #     - ./ops/init:/docker-entrypoint-initdb.d
  #     - ./ops/data:/docker-entrypoint-initdb.d/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
  #     interval: 3s
  #     timeout: 3s
  #     retries: 20
  
  db:
    build:
      context: .
      dockerfile: pg.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ops/init:/docker-entrypoint-initdb.d
      - ./ops/data:/docker-entrypoint-initdb.d/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 3s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: ["tools"]

  langflow:
    image: langflowai/langflow:1.5.1
    depends_on:
      db:
        condition: service_healthy
    user: "0:0"   # запускаем от root, чтобы точно были права на запись
    environment:
      LANGFLOW_DATABASE_URL: postgresql://app:app@db:5432/app
      LANGFLOW_AUTO_LOGIN: "true"
      LANGFLOW_SECRET_KEY: ${LANGFLOW_SECRET_KEY:-change-me}
      LANGFLOW_CONFIG_DIR: /app/.langflow        # <— внутренняя папка
      LANGFLOW_LOAD_FLOWS_PATH: /app/flows       # <— сюда монтируем ваши .json
    volumes:
      - ./flows:/app/flows:ro
      - langflow_data:/app/.langflow             # <— volume на внутр. каталог
    ports:
      - "7860:7860"
    # НИКАКИХ entrypoint/command с chmod больше не нужно

volumes:
  pgdata:
  langflow_data:
